### ISSUE TITLE
Add blog channel summary - display in sidebar of Blog channel AND related blog posts as per the GDS blog

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_blogs#4]
There will be a body field on the Blog channel. We'd like to display this in the sidebar of the Blog Channel.
We'd also like to display this in the sidebar of any Blog post which belongs to that channel. 

as per: 

![image](https://user-images.githubusercontent.com/3852805/192542066-41f65a49-7855-4c6e-92f7-ac4d0bbcffa8.png)

**Comment by msayoung** [comment]
the blog channel summary is added: https://github.com/localgovdrupal/localgov_blogs/pull/6

**Comment by msayoung** [comment]
@willguv 

On microsites, where we are offering the various columns and layouts - some of which can be full screen - this sidebar information doesn't really work. 

What should we do with the sidebar information?

**Comment by msayoung** [comment]
Perhaps we should just not display it in microsites?

**Comment by willguv** [comment]
@msayoung I assumed microsite blogs would always have a wide column of content with a narrow sidebar of related info

Do you have an example of where this is not the case?

I’m thinking if there’s a sidebar show the info, if not don’t
