### ISSUE TITLE
Blog Teaser display

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_blogs#9]
After discussion with @willguv - we are suggesting to go for a pattern that is a mix of GDS and medium for the teaser display of blogs. 

![image](https://user-images.githubusercontent.com/3852805/192544904-fc96e069-c772-4822-8c6f-25d24ef440cd.png)

https://miro.com/app/board/uXjVOStMNW8=/?moveToWidget=3458764534399942518&cot=14

The difference to our 'normal' pattern is that we have the image on the right, and a bit smaller. We'll also show some other metadata.

We'd also like an alternative teaser view which shows the Blog channel the post belongs to, which is the default display for all places except on the Blog channel page. 

@markconroy how do you feel about this? 

Would it be better to keep the pattern more similar across all the teasers, or is it ok to have a different pattern in this case?

**Comment by finnlewis** [comment]
Sprint planning discussion: we're liking this layout. Also thinking that images might be optional , so this layout works well fo both.

**Comment by markconroy** [comment]
This layout looks good to me. If we use the `node--teaser.html.twig` file, the only change in CSS we'll need will be something like this:

```
.lgd-teaser--blog {
    flex-direction: row-reverse;
}
```
